### PR TITLE
Replaced the code with a shorter implementation

### PR DESCRIPTION
**Pull request by metaa**

### CODE REVIEW

**Comment by EldonMcGuinness** [comment]
I've checked this PR against the JSFiddle and the results are not the same, as such there must be something wrong here. Feel free to correct and resubmit.

**Expected Output**
```
{
  "foo": [
    "bar",
    "boo"
  ],
  "roo": "bar",
  "bee": "bop",
  "": [
    "ghost",
    "ghost2"
  ],
  "checkbox[]": [
    "b1",
    "b2"
  ],
  "dd": null,
  "http": [
    "http://w3schools.com/my test.asp?name=ståle&car=saab",
    "http://w3schools2.com/my test.asp?name=ståle&car=saab"
  ]
}
```

**Your Output**
```
{
  "www.google.com/?foo": "bar",
  "foo": "boo",
  "roo": "bar;bee=bop;=ghost;=ghost2;",
  ";checkbox%5B%5D": "b1;checkbox%5B%5D=b2;dd=;http=http%3A%2F%2Fw3schools.com%2Fmy%20test.asp%3Fname%3Dst%C3%A5le%26car%3Dsaab",
  "http": "http%3A%2F%2Fw3schools2.com%2Fmy%20test.asp%3Fname%3Dst%C3%A5le%26car%3Dsaab"
}
```

**Comment by EldonMcGuinness** [comment]
``

**Comment by metaa** [comment]
Ah, I didn't see that fiddle, so I just tested with random values that worked so far.
What didn't go into my code was handling a domain in front of the query strings aswell.

I updated my code now to accomodate for that problem, but:

Technically speaking, the output that your code produces is plain wrong.
You clean up the trash for the user, thus you turn the passed query strings into an object carrying GET parameters that technically couldn't exist there because of how those should actually be handled.

My code handles the GET params just as you pass them, so if you got a semicolon after an ampersand, then that's what you get.

If we take a look at what PHP produces with your query string in your test code, this is the output:
```
Array
(
    [foo] => boo
    [roo] => bar;bee=bop;=ghost;=ghost2;
    [;checkbox] => Array
        (
            [0] => b1;checkbox[]=b2;dd=;http=http://w3schools.com/my test.asp?name=ståle&car=saab
        )

    [http] => http://w3schools2.com/my test.asp?name=ståle&car=saab
)
```

Passing a parameter with `[]` indicates an array and usually will be handled as such by web applications, but both yours and mine code take that into the `key` part of the object.

What we also ignore here is, that passing a parameter twice should actually override it instead of turning that into an array. In my original approach to replace your code I decided to go what yours output, though, so that's up to you if you want to go by **what web servers would return** to you or if you just want a list of **what is in the string** you pass.

Please let me know what you think of this, feedback is appreciated of course.

**Comment by EldonMcGuinness** [comment]
Hey, that was quick! According to the [W3C recommendation](https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2), "HTTP server implementors, and in particular, CGI implementors support the use of ";" in place of "&" to save authors the trouble of escaping "&" characters in this manner." As such, I convert the ";" to an ampersand to make sure all the items are parsed properly instead of handling them separately. While I do realize that in practice most people do not use the ";" as a query-string separator, this script needs to be as universal as possible so I stick with the W3C rules and recommendations. 

When it comes to arrays of items, I am inclined to agree with you, that unless there is an agreed upon notation for arrays of query-string items we should just flatten them with the last one taking precedence. However, after much consideration and discussion on another forum over a year ago, it was the general consensus that allowing access to all values passed in an array format would be best as some applications do use this and there is not a standardized way to denote if an item should be an array or string.

Finally, I liked your idea of cleaning up the script a bit and had some time to use today and did that as well as implementing Travis CI on the script to ensure it is tested on future PRs.

**Pull request closed without merging**
